inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  DisplayStyleGuide: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/FormatString:
  EnforcedStyle: percent

Style/DoubleNegation:
  Enabled: false

Style/RescueModifier:
  Enabled: false

# Disable these temporarily while they're in .rubocop_todo.yml
# Metrics/LineLength:
#   Max: 100
#
# Metrics/MethodLength:
#   Max: 15
