# frozen_string_literal: true

source "https://rubygems.org"

gem "grinch", ">= 1.0.1"
gem "grinch-identify"
gem "daemons"
gem "duck-duck-go"
gem "flippy"
gem "genregen"
gem "goodreads"
gem "haste"
gem "htmlentities"
gem "json"
gem "lastfm"
gem "leetspeak"
gem "mechanize"
gem "myanimelist", "~> 1.0"
gem "nokogiri"
gem "open_uri_redirections"
gem "research_topicgen"
gem "ruby-eval-in"
gem "ruby-upworthy"
gem "sanitize", "~> 5.0.0"
gem "telegraph"
gem "time_difference"
gem "wolfram"
gem "xkcd"
gem 'apixu', git: 'https://github.com/apixu/apixu-ruby.git', branch: 'master', ref: "52d5408"
