# frozen_string_literal: true

source "https://rubygems.org"

gem "daemons"
gem "duck-duck-go"
gem "flippy"
gem "genregen"
gem "grinch", "~> 1.1"
gem "grinch-identify", "~> 1.8"
gem "haste"
gem "htmlentities"
gem "json"
gem "lastfm"
gem "leetspeak"
gem "mechanize"
gem "myanimelist", "~> 1.0"
gem "nokogiri"
gem "open_uri_redirections"
gem "research_topicgen"
gem "ruby-eval-in"
gem "ruby-upworthy"
gem "sanitize", "~> 5.2.3"
gem "telegraph"
gem "time_difference"
gem "wolfram"
gem "xkcd"
